baseURL = "https://theovanblommestein.github.io/"
languageCode = "en-us"
title = "Theo van Blommestein"
theme = "typo"

[params]
homeIntroTitle = 'Greetings!'

homeIntroContent = """
My name is Theo van Blommestein (or Theodorus van Blommestein if you want to spite me). 
I grew up in the Bay Area and I love magical realism and sci-fi. I am a Pre-med from Duke University.
My heritage is a bit all over the place. Maybe I'll include it some other time. 
The last name is Dutch-Indonesian.
"""

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"

[[params.social]]
name = "medium"
url = "https://medium.com/@user"

homeCollectionTitle = 'Posts'
homeCollection = 'posts'